### ISSUE TITLE
v2 Features

### ISSUE THREAD

**Issue by GrahamSH-LLK** [snapwiki/SnapProjectEmbed#12]
* [x] Enable toggling of values such as 

	-  [x] Project title and author
	-  [x] Edit button
	-  [x] Pause button

* [x] Ability to use ``` <details> <summary> </summary></details> ```
	
* [x] Linking the MediaWiki page instead of this repository

* [x] Adding a class ("snap-project") to the rendered iframe

* [x] Adding new parser hook "snap-project"

* [x]  Add qqq.json

* [x] Make renderEmbedSnap a public static function
* [x]  Change extension display name to "Snap! Project Embed"

**Comment by R4356th** [comment]
" Enable toggling of values such as" -what do you mean by this?

**Comment by GrahamSH-LLK** [comment]
> " Enable toggling of values such as" -what do you mean by this?

You could add a value like ```` editbutton="false" ``` to remove the edit button, or reverse to add it. I forget what the default is. 

This is what the second one is like:
<details>
<summary>Details</summary>
<iframe>...</iframe>


</details>

**Comment by R4356th** [comment]
By edit button do you mean the See Code option or what? And I am confused about the "details" tag. Did GitHub render it in a wrong way or did you intentionally hide the summary (like on the forums)?

**Comment by R4356th** [comment]
@GrahamSH-LLK ?

**Comment by GrahamSH-LLK** [comment]
> By edit button do you mean the See Code option or what? And I am confused about the "details" tag. Did GitHub render it in a wrong way or did you intentionally hide the summary (like on the forums)?

Oh, sorry. Yeah, I wanted a collapsible feature so that it doesn't take up tons of space. And yes, I mean the see code. I mostly copied that from Snap!'s embed options.

**Comment by R4356th** [comment]
Okay. I did some research and it looks like we could use the HTML ``details`` tag.

**Comment by GrahamSH-LLK** [comment]
> Okay. I did some research and it looks like we could use the HTML `details` tag.

That's exactly what I used there!

**Comment by R4356th** [comment]
I am merging v2 into master. I will finish the only feature that is left (ability to use the details and summary tags) soon and release a new version.

**Comment by R4356th** [comment]
We have not updated the MW.org page. This should be a high priority task.

**Comment by GrahamSH-LLK** [comment]
Okay

**Comment by R4356th** [comment]
With #30 now merged, all features have finally been implemented!
