### ISSUE TITLE
Polish localization proposal

### ISSUE THREAD

**Issue by DarDoro** [snapwiki/SnapProjectEmbed#14]
i18n\pl.json

{
  "@metadata": {
    "autor": "R4356th, GrahamSH, mw-embedScratch współautorzy"
  },
  "embedsnap-desc": "Osadzanie projektu Snap!",
  "error-project": "<p style=\"color:red;\">Błąd: brak nazwy projektu</p>",
  "error-username": "<p style=\"color:red;\">Błąd: brak nazwy użytkownika</p>"
}

**Comment by R4356th** [comment]
Considering you already have made a fork, could you please directly send a PR? I could add it myself if you have any problem though. :)

**Comment by DarDoro** [comment]
Done PR #15
