### ISSUE TITLE
Setup Better CI

### ISSUE THREAD

**Issue by R4356th** [snapwiki/SnapProjectEmbed#27]
We should consider using Phan and PHP Code Sniffer (the one published by Wikimedia) instead of GitHub Actions and Prettier as those are widely used, well maintained and good for security.

Tasks:

- [x] Set up Phan
- [x] Set up PHP CS
- [ ] Set up PHP Parallel Lint

**Comment by GrahamSH-LLK** [comment]
Phan can be easily used in GH Actions as one of the tools in the tools section of setup-php
I'm not sure about PHP Code Sniffier

**Comment by R4356th** [comment]
Cool but where would the result be logged? Phan can catch security issues as well which should obviously not be public. As for Code Sniffier, I have read MediaWiki  documentation and it looks pretty simple.

**Comment by R4356th** [comment]
PHPCS has also been set up. I just added PHP Parallel Lint to the list. This would be done soon.
